
name: Build

on:
  push:
    branches-ignore: [ master ]

jobs:
  build:
    name: Build
    permissions:
      contents: read
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
