
name: Nightly

on:
  push:
#  schedule:
#    - cron: "59 23 * * *"

jobs:
  build:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
