
on: pull_request

jobs:
  testBinaries:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: test_binary (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run: { shell: bash }
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          distribution: graalvm-community
          java-version: 21
          cache: gradle
      - run: ./gradlew nativeTest
      - run: ./gradlew zipNative
      - if: ${{ matrix.os == 'windows-latest' }}
        run: |
          chmod +x build/native/nativeCompile/codecv.exe
          ./build/native/nativeCompile/codecv.exe serve examples/full.cv.json &
      - if: ${{ matrix.os != 'windows-latest' }}
        run: |
          chmod +x build/native/nativeCompile/codecv
          ./build/native/nativeCompile/codecv serve examples/full.cv.json &
      - if: ${{ matrix.os != 'windows-latest' }}
        run: curl http://localhost:2010/openapi.yml
