
name: Test Binaries

on: pull_request

jobs:
  testBinaries:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Binary (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run: { shell: bash }
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle
      - name: Run Tests
        run: ./gradlew test
      - name: Build Native
        run: ./gradlew zipNative
      - name: Start Native (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          chmod +x build/native/nativeCompile/codecv.exe
          ./build/native/nativeCompile/codecv.exe &
      - name: Start Native (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          chmod +x build/native/nativeCompile/codecv
          ./build/native/nativeCompile/codecv &
      - name: Test Native (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: curl http://localhost:2010/openapi.yml
