
name: Push

on:
  push:
    branches-ignore: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/gradle
      - name: Check Build
        run: ls -AlF build
